# Generated by Django 2.2.4 on 2021-11-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('virtual_money', models.FloatField(verbose_name='虚拟金额')),
                ('own_money', models.FloatField(verbose_name='实际金额')),
                ('virtual_borrow_money', models.FloatField(verbose_name='虚拟借款金额')),
                ('borrow_money', models.FloatField(verbose_name='实际借款金额')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
