# Generated by Django 2.2.4 on 2021-11-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='borrow_money',
            field=models.FloatField(default=0, max_length=100, verbose_name='实际借款金额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='own_money',
            field=models.FloatField(default=0, max_length=100, verbose_name='实际金额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='virtual_borrow_money',
            field=models.FloatField(default=0, max_length=100, verbose_name='虚拟借款金额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='virtual_money',
            field=models.FloatField(default=0, max_length=100, verbose_name='虚拟金额'),
        ),
    ]
