# Generated by Django 2.2.4 on 2021-11-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211101_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-id',)},
        ),
    ]
