# Generated by Django 2.2.4 on 2021-08-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210824_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
