# Generated by Django 2.2.4 on 2021-08-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210824_0842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
