# Generated by Django 2.2.4 on 2021-11-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210825_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(help_text='测试用名称', max_length=10, verbose_name='名称'),
        ),
    ]
